[build]
  command = "echo 'No build command'"  # Non è necessaria alcuna build specifica per il tuo caso
  publish = "."  # Pubblica dalla directory corrente (root del progetto)

[[redirects]]
  from = "/api/*"
  to = "https://appgis.onrender.com/api/:splat"
  status = 200
  force = true
