[build]
  base = "frontend"  # Modifica questa sezione con la cartella giusta, se la tua cartella del frontend è diversa
  publish = "frontend"  # La cartella dove Netlify pubblicherà i file
  command = "echo 'No build command'"  # Comando di build, se non serve puoi lasciarlo come questo

[[redirects]]
  from = "/api/*"
  to = "https://appgis.onrender.com/api/:splat"
  status = 200
  force = true
